### ISSUE TITLE
FS crashed

### ISSUE THREAD

**Issue by padak** [korczis/gooddata-rust#1]
Ahoj,
when mounting fs under my "dev" GD account `petr@simecek.org` (with admin access to just one GB project), everything seem to be OK, until I open ./projects directory. This is "logs" from my stdout:

```
[ec2-user@kbc-devel-02 gooddata-rust]$ /home/ec2-user/.cargo/bin/gooddata-rust petr@simecek.org xxxx /mnt/gooddata-fuse/
Response { status: Ok, headers: Headers { Age: 0, Via: 1.1 varnish, X-GDC-LOG-HEADER: , X-Varnish: 1709785777, X-GDC-REQUEST-TIME: 8, Connection: keep-alive, Server: GoodData WebApp, P3P: CP='IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT', Pragma: no-cache, Cache-Control: no-store, no-cache, must-revalidate, max-age=0, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Content-Length: 2, X-GDC-REQUEST: Os742FuaM3nPzf6n, Date: Fri, 27 May 2016 21:57:49 GMT, Content-Type: application/json, Set-Cookie: GDCAuthTT=LizC2aOCuVJNwjwitVAdK2FdY-U3c6syqnWBHajCmPppZcPZa7aktC0GclN8ZeZrgI3TA4gvSUGkOQNXcT3MllP2ZvlveHwgsf3mCyMsygh5pC3AaDOw_-JiQEZWmj_L5dn_q2R_B5_tD6lVs7KBxpVtZ3JzSilauhJDwMlxRr97InUiOiIzNTgyIiwidiI6MTQ2NDM4Njg2OSwiayI6IjYxMGNlYmRkLTZkNjgtNDFmOC1hYmRhLTIyY2QxMTRlZTIxZiIsImwiOiIwIn0; Path=/gdc; Secure; HttpOnly, Accept-Ranges: bytes, }, version: Http11, url: "https://secure.gooddata.com/gdc/account/token", status_raw: RawStatus(200, "OK"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(SizedReader(remaining=2))) } } }
Response { status: Ok, headers: Headers { X-GDC-REQUEST-TIME: 24, Cache-Control: no-cache, no-store, must-revalidate, Content-Length: 499, Date: Fri, 27 May 2016 21:57:49 GMT, Content-Type: application/json;charset=UTF-8, Via: 1.1 varnish, X-Varnish: 1818368743, Age: 0, X-GDC-REQUEST: MkFDHlvaDh9sHygM, Server: GoodData WebApp, X-GDC-LOG-HEADER: , Connection: keep-alive, Accept-Ranges: bytes, }, version: Http11, url: "https://secure.gooddata.com/gdc/account/profile/c01bb157fd31678fb407bc3e76816144", status_raw: RawStatus(200, "OK"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(SizedReader(remaining=499))) } } }
Mounting GoodData as Filesystem, mountpoint: /mnt/gooddata-fuse/

GoodDataFS::getattr() - Reading inode 1
GoodDataFS::getattr() - Reading inode 1
GoodDataFS::lookup() - Reading parent 1, path ".rvmrc"
GoodDataFS::lookup() - Reading parent 1, path ".versions.conf"
GoodDataFS::lookup() - Reading parent 1, path ".ruby-version"
GoodDataFS::lookup() - Reading parent 1, path ".rbfu-version"
GoodDataFS::lookup() - Reading parent 1, path ".rbenv-version"
GoodDataFS::lookup() - Reading parent 1, path "Gemfile"
GoodDataFS::readdir() - Reading inode 1
GoodDataFS::lookup() - Reading parent 1, path "user.json"
GoodDataFS::lookup() - Reading parent 1, path "projects"
GoodDataFS::readdir() - Reading inode 1
GoodDataFS::lookup() - Reading parent 1, path "user.json"
GoodDataFS::getattr() - Reading inode 1
GoodDataFS::read() - Reading inode 2
GoodDataFS::getattr() - Reading inode 2
GoodDataFS::read() - Reading inode 2
GoodDataFS::getattr() - Reading inode 2
GoodDataFS::lookup() - Reading parent 1, path "projects"
GoodDataFS::getattr() - Reading inode 1
GoodDataFS::lookup() - Reading parent 3, path ".rvmrc"
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Unmounting GoodData Filesystem
Disconnecting from GoodData Platform
[ec2-user@kbc-devel-02 gooddata-rust]$ 
```

You might want to have anything else...

Anyway, this is very cool project! Fingers crossed!

Petr

**Comment by korczis** [comment]
@padak Fixed in latest version.

**Comment by korczis** [comment]
Fixed in ac9432fef18044add0dcd909a2b3492477fd2ec9

**Comment by korczis** [comment]
@padak Btw what OS do you use? Linux or mac?

**Comment by korczis** [comment]
@padak Btw it seems you mounted GD FS into non-empty folder, is that right?

**Comment by padak** [comment]
Hi! I'm playing w/ it on default Amazon Linux image. Mount point was empty. Will update and test it this evening! Thanks, Peter

**Comment by korczis** [comment]
Strange, according to logs you provided it seems you should see something in your "mountpoint". I fixed crash caused by `Err(Io(Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("Connection closed") }) }))`. 

Please, feel free to test new version and let me know if it works.

PS: Best way to run this piece of SW is: `RUST_BACKTRACE=1 RUST_LOG=debug gooddata-fs joe.doe@gooddata.com secretpassword /Users/joe.doe/gd
`

When launched in this way it provides callstack/backtrace information (which is very useful for debugging) in case of sad crash scenario.

PPS: Beware that only items marked with `✓` are implemeted already - https://github.com/korczis/gooddata-rust/blob/master/doc/Filesystem.md#root

**Comment by padak** [comment]
I'm on it! Sorry for yesterday, I crashed after long weekend :)

**Comment by padak** [comment]
Something weird is happening inside project folder:
![image](https://cloud.githubusercontent.com/assets/1427901/15645531/4b7a9cfe-2659-11e6-99e2-71cd91fb2101.png)

Give me your public ssh key and I'll share you my DigitalOcean instance (purely openned just for this test).

**Comment by korczis** [comment]
Hi,

my key is: 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB09q11KKRPQDrioesdIQRst7FLZMmSNUBvS7GCvUapAZ253QMO1+akEletdrFMtnZ53FG+r756hWUG5157Xq3p2RJkM9/vI9MIovTM0SnzP7mHwvrzRThomZ600l4on8Xi/pET47dkV9MxADR/RAKo5cmc3N1/jYhB8v5U18AfDGYKBpqvp2yyIOX0Ems8ULFzNAnUXWqFWS2sQxZmVp69Y18gxYZ9iqtxEK8vGjLKkJpPnkyceqmVfydgoTCAHdpgmALgjtSmUsrvpCugpJ/1G/gAR6JOoxM75yf3/1lji/cWlUyeQZfa9E+yj6R8Cd3pd9BjwC14l7qjhP+JBkh korczis@gmail.com
```

PS: I will not be able to investigate this sooner than today evening.

Thanks for help

**Comment by padak** [comment]
No probl! 
1. `ssh root@107.170.114.29`
2. `ls -la /mnt/gd/projects/KBC\ Internal\ Stats/` answer with error
3. `gooddata-fs` is in screen (`screen -r`)
4. my gd user used for test has access to our internal project only, please handle it securely

P.

**Comment by korczis** [comment]
Thanks, I have fixed problem with projects/$PROJECT_NAME/project.json and everything seems to be working correctly.

PS: Ignore files with ? as they are not fully implemented yet
- featureflags.json
- roles.json
- permissions.json
